//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36279
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionStones.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FashionStones.App_LocalResources.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пароля.
        /// </summary>
        public static string ChangePasswordViewModelConfirmPassword {
            get {
                return ResourceManager.GetString("ChangePasswordViewModelConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        public static string ChangePasswordViewModelNewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordViewModelNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string ChangePasswordViewModelOldPassword {
            get {
                return ResourceManager.GetString("ChangePasswordViewModelOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string CoutryName {
            get {
                return ResourceManager.GetString("CoutryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес доставки.
        /// </summary>
        public static string DeliveryAddress {
            get {
                return ResourceManager.GetString("DeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string DiscountName {
            get {
                return ResourceManager.GetString("DiscountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение.
        /// </summary>
        public static string DiscountValue {
            get {
                return ResourceManager.GetString("DiscountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введеные пароли не совпадают.
        /// </summary>
        public static string ErrorMessageCompareChangePasswordViewModelConfirmPassword {
            get {
                return ResourceManager.GetString("ErrorMessageCompareChangePasswordViewModelConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат E-mail.
        /// </summary>
        public static string ErrorMessageRegularExpressionEmail {
            get {
                return ResourceManager.GetString("ErrorMessageRegularExpressionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите новый пароль.
        /// </summary>
        public static string ErrorMessageRequiredChangePasswordViewModelNewPassword {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredChangePasswordViewModelNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        public static string ErrorMessageRequiredChangePasswordViewModelOldPassword {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredChangePasswordViewModelOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Адрес доставки.
        /// </summary>
        public static string ErrorMessageRequiredDeliveryAdress {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredDeliveryAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Количество.
        /// </summary>
        public static string ErrorMessageRequiredJewelCount {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredJewelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите Покрытие.
        /// </summary>
        public static string ErrorMessageRequiredJewelCover {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredJewelCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Диаметр.
        /// </summary>
        public static string ErrorMessageRequiredJewelDiameter {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredJewelDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Длину.
        /// </summary>
        public static string ErrorMessageRequiredJewelLenght {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredJewelLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите Наценку.
        /// </summary>
        public static string ErrorMessageRequiredJewelMarkup {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredJewelMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите Материал.
        /// </summary>
        public static string ErrorMessageRequiredJewelMaterial {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredJewelMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Название.
        /// </summary>
        public static string ErrorMessageRequiredJewelName {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredJewelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите Фото.
        /// </summary>
        public static string ErrorMessageRequiredJewelPhoto {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredJewelPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Название.
        /// </summary>
        public static string ErrorMessageRequiredJewelPhotoCaption {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredJewelPhotoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Цену.
        /// </summary>
        public static string ErrorMessageRequiredJewelPrice {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredJewelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Качество.
        /// </summary>
        public static string ErrorMessageRequiredJewelQuality {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredJewelQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Размер.
        /// </summary>
        public static string ErrorMessageRequiredJewelSize {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredJewelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите Камень.
        /// </summary>
        public static string ErrorMessageRequiredJewelStone {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredJewelStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Оптовую цену.
        /// </summary>
        public static string ErrorMessageRequiredJewelTradePrice {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredJewelTradePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Вес.
        /// </summary>
        public static string ErrorMessageRequiredJewelWeight {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredJewelWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер заказа.
        /// </summary>
        public static string ErrorMessageRequiredJInformPaymentViewModelOrderId {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredJInformPaymentViewModelOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер телефона.
        /// </summary>
        public static string ErrorMessageRequiredJInformPaymentViewModelPhoneNumber {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredJInformPaymentViewModelPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите время платежа.
        /// </summary>
        public static string ErrorMessageRequiredJInformPaymentViewModelTimePay {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredJInformPaymentViewModelTimePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите сумму оплаты.
        /// </summary>
        public static string ErrorMessageRequiredJInformPaymentViewModelTotal {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredJInformPaymentViewModelTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Розничную наценку.
        /// </summary>
        public static string ErrorMessageRequiredRetaulMarkup {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredRetaulMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Название камня.
        /// </summary>
        public static string ErrorMessageRequiredStoneName {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredStoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Оптовую наценку.
        /// </summary>
        public static string ErrorMessageRequiredTradeMarkup {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredTradeMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Город.
        /// </summary>
        public static string ErrorMessageRequiredUserCity {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredUserCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Страну.
        /// </summary>
        public static string ErrorMessageRequiredUserCoutry {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredUserCoutry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите E-mail.
        /// </summary>
        public static string ErrorMessageRequiredUserEmail {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Имя.
        /// </summary>
        public static string ErrorMessageRequiredUserFirstName {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredUserFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Фамилию.
        /// </summary>
        public static string ErrorMessageRequiredUserLastName {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredUserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Логин.
        /// </summary>
        public static string ErrorMessageRequiredUserLogin {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Отчество.
        /// </summary>
        public static string ErrorMessageRequiredUserMiddleName {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredUserMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Пароль.
        /// </summary>
        public static string ErrorMessageRequiredUserPassword {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите телефон.
        /// </summary>
        public static string ErrorMessageRequiredUserPhone {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredUserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите Номер телефона.
        /// </summary>
        public static string ErrorMessageRequiredUserPhoneNumber {
            get {
                return ResourceManager.GetString("ErrorMessageRequiredUserPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер заказа.
        /// </summary>
        public static string InformPaymentViewModelOrderId {
            get {
                return ResourceManager.GetString("InformPaymentViewModelOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефона.
        /// </summary>
        public static string InformPaymentViewModelPhoneNumber {
            get {
                return ResourceManager.GetString("InformPaymentViewModelPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время платежа.
        /// </summary>
        public static string InformPaymentViewModelTimePay {
            get {
                return ResourceManager.GetString("InformPaymentViewModelTimePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма оплаты.
        /// </summary>
        public static string InformPaymentViewModelTotal {
            get {
                return ResourceManager.GetString("InformPaymentViewModelTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string JewelPhotoCaption {
            get {
                return ResourceManager.GetString("JewelPhotoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string MarkupName {
            get {
                return ResourceManager.GetString("MarkupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розничная наценка.
        /// </summary>
        public static string MarkupRetailMarkup {
            get {
                return ResourceManager.GetString("MarkupRetailMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оптовая наценка.
        /// </summary>
        public static string MarkupTradeMarkup {
            get {
                return ResourceManager.GetString("MarkupTradeMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод доставки.
        /// </summary>
        public static string MethodOfDeliveryName {
            get {
                return ResourceManager.GetString("MethodOfDeliveryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод оплаты.
        /// </summary>
        public static string MethodOfPaymentName {
            get {
                return ResourceManager.GetString("MethodOfPaymentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        public static string OrderCity {
            get {
                return ResourceManager.GetString("OrderCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна.
        /// </summary>
        public static string OrderCountry {
            get {
                return ResourceManager.GetString("OrderCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время заказа.
        /// </summary>
        public static string OrderDataTime {
            get {
                return ResourceManager.GetString("OrderDataTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Способ доставки.
        /// </summary>
        public static string OrderMethodOfDeliveryId {
            get {
                return ResourceManager.GetString("OrderMethodOfDeliveryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Способ оплаты.
        /// </summary>
        public static string OrderMethodOfPaymentId {
            get {
                return ResourceManager.GetString("OrderMethodOfPaymentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string OrderTextInfo {
            get {
                return ResourceManager.GetString("OrderTextInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общая сумма (грн).
        /// </summary>
        public static string OrderTotalCount {
            get {
                return ResourceManager.GetString("OrderTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string ProductCategoryId {
            get {
                return ResourceManager.GetString("ProductCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string ProductCount {
            get {
                return ResourceManager.GetString("ProductCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покрытие.
        /// </summary>
        public static string ProductCover {
            get {
                return ResourceManager.GetString("ProductCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покрытие.
        /// </summary>
        public static string ProductCoverId {
            get {
                return ResourceManager.GetString("ProductCoverId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата добавления.
        /// </summary>
        public static string ProductDateOfPublishing {
            get {
                return ResourceManager.GetString("ProductDateOfPublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диаметр.
        /// </summary>
        public static string ProductDiameter {
            get {
                return ResourceManager.GetString("ProductDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скидка.
        /// </summary>
        public static string ProductDiscount {
            get {
                return ResourceManager.GetString("ProductDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скидка.
        /// </summary>
        public static string ProductDiscountId {
            get {
                return ResourceManager.GetString("ProductDiscountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина.
        /// </summary>
        public static string ProductLenght {
            get {
                return ResourceManager.GetString("ProductLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наценка.
        /// </summary>
        public static string ProductMarkupId {
            get {
                return ResourceManager.GetString("ProductMarkupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Материал.
        /// </summary>
        public static string ProductMaterial {
            get {
                return ResourceManager.GetString("ProductMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Материал.
        /// </summary>
        public static string ProductMaterialId {
            get {
                return ResourceManager.GetString("ProductMaterialId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото.
        /// </summary>
        public static string ProductPHotoId {
            get {
                return ResourceManager.GetString("ProductPHotoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Качество.
        /// </summary>
        public static string ProductQuality {
            get {
                return ResourceManager.GetString("ProductQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество на складе.
        /// </summary>
        public static string ProductQuantityInStock {
            get {
                return ResourceManager.GetString("ProductQuantityInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розничная цена.
        /// </summary>
        public static string ProductRetailPrice {
            get {
                return ResourceManager.GetString("ProductRetailPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер.
        /// </summary>
        public static string ProductSize {
            get {
                return ResourceManager.GetString("ProductSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Камень.
        /// </summary>
        public static string ProductStone {
            get {
                return ResourceManager.GetString("ProductStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оптовая цена.
        /// </summary>
        public static string ProductTradePrice {
            get {
                return ResourceManager.GetString("ProductTradePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вес.
        /// </summary>
        public static string ProductWeight {
            get {
                return ResourceManager.GetString("ProductWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        public static string UserCity {
            get {
                return ResourceManager.GetString("UserCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна.
        /// </summary>
        public static string UserCoutrry {
            get {
                return ResourceManager.GetString("UserCoutrry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string UserFirstName {
            get {
                return ResourceManager.GetString("UserFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИНН.
        /// </summary>
        public static string UserInn {
            get {
                return ResourceManager.GetString("UserInn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид деятельности.
        /// </summary>
        public static string UserKindOfActivity {
            get {
                return ResourceManager.GetString("UserKindOfActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string UserLastName {
            get {
                return ResourceManager.GetString("UserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string UserMiddleName {
            get {
                return ResourceManager.GetString("UserMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите пароль.
        /// </summary>
        public static string UserPasswordRepeat {
            get {
                return ResourceManager.GetString("UserPasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моб. Телефон.
        /// </summary>
        public static string UserPhone {
            get {
                return ResourceManager.GetString("UserPhone", resourceCulture);
            }
        }
    }
}
